<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>TotalWine</groupId>
  <artifactId>rahul_test_app</artifactId>
  <version>1.0.0</version>
  <packaging>kjar</packaging>
  <name>totlwine.rahul_test_app</name>
  <description></description>
  <organization>
    <name>Kibo Software</name>
    <url>http://www.kibocommerce.com</url>
  </organization>
  <developers>
    <developer>
      <id>kibocommerce.com</id>
      <name>Kibo Software</name>
      <organization>Kibo Software</organization>
      <organizationUrl>http://www.kibocommerce.com</organizationUrl>
    </developer>
  </developers>
  <properties>
    <maven.compiler.release>${java.version}</maven.compiler.release>
    <sonar.projectName>Kibo.FulfillmentWorkflows</sonar.projectName>
    <kotlin.version>1.5.10</kotlin.version>
    <maven-release-plugin.version>2.5.3</maven-release-plugin.version>
    <sonar.login>${env.SONAR_LOGIN}</sonar.login>
    <sonar.projectVersion>${project.version}</sonar.projectVersion>
    <sonar.scm.disabled>true</sonar.scm.disabled>
    <sonar.scm.provider>git</sonar.scm.provider>
    <sonar.sources>${project.build.sourceDirectory}</sonar.sources>
    <!--sonar.tests>${project.build.testSourceDirectory}</sonar.tests-->
    <sonar.language>java</sonar.language>
    <sonar.java.source>${java.version}</sonar.java.source>
    <jackson.version>2.9.7</jackson.version>
    <version.org.kie>7.26.0.Final</version.org.kie>
    <maven-dependency-plugin.version>3.1.2</maven-dependency-plugin.version>
    <sonar.exclusions>**/*.xml, **/*Test.*</sonar.exclusions>
    <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
    <sonar.tests>${project.build.testSourceDirectory}</sonar.tests>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <jacocoOutputDirectory>${project.build.directory}/jacoco-aggregate</jacocoOutputDirectory>
    <sonar.coverage.jacoco.xmlReportPaths>${jacocoOutputDirectory}/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
    <sonar.coverage.exclusions>${sonar.tests}/**/*</sonar.coverage.exclusions>
    <sonar.language>java</sonar.language>
    <java.version>8</java.version>
    <sonar.organization>kibo-ucp</sonar.organization>
    <sonar.sources>${project.build.sourceDirectory}</sonar.sources>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <sonar.scm.provider>git</sonar.scm.provider>
    <sonar.scm.disabled>true</sonar.scm.disabled>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.jbpm</groupId>
      <artifactId>jbpm-workitems-rest</artifactId>
      <version>7.74.1.Final</version>
    </dependency>
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-internal</artifactId>
      <version>${version.org.kie}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.thoughtworks.xstream</groupId>
      <artifactId>xstream</artifactId>
      <version>1.4.10</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jbpm</groupId>
      <artifactId>jbpm-test</artifactId>
      <version>${version.org.kie}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>${kotlin.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-test-junit</artifactId>
      <version>${kotlin.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.kie</groupId>
        <artifactId>kie-maven-plugin</artifactId>
        <version>${version.org.kie}</version>
        <extensions>true</extensions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>compile</id>
          </execution>
        </executions>
        <configuration>
          <release>${java.version}</release>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <excludes>
            <exclude>target/**</exclude>
          </excludes>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <version>${maven-release-plugin.version}</version>
        <configuration>
          <useReleaseProfile>false</useReleaseProfile>
          <autoVersionSubmodules>true</autoVersionSubmodules>
          <tagNameFormat>v@{version}</tagNameFormat>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>test-compile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <jvmTarget>1.8</jvmTarget>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.9</version>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
            <configuration>
              <formats>
                <format>XML</format>
              </formats>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <excludes>
            <exclude>**/*Test*</exclude>
          </excludes>
          <outputDirectory>${jacocoOutputDirectory}</outputDirectory>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
        <version>3.9.1.2184</version>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>ignorebpmtests</id>
      <properties>
        <skipTests>true</skipTests>
        <maven.test.skip>true</maven.test.skip>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
      </properties>
    </profile>
    <profile>
      <id>nexus-deploy</id>
      <activation />
      <distributionManagement>
        <repository>
          <id>kibo-businessautomation-releases</id>
          <name>Kibo BusinessAutomation Releases</name>
          <url>https://nexus.kibo-dev-ext.com/repository/kibo-businessautomation-releases</url>
        </repository>
        <snapshotRepository>
          <id>kibo-businessautomation-snapshots</id>
          <name>Kibo BusinessAutomation Snapshots</name>
          <url>https://nexus.kibo-dev-ext.com/repository/kibo-businessautomation-snapshots</url>
        </snapshotRepository>
      </distributionManagement>
    </profile>
    <profile>
      <id>devcenter</id>
      <activation>
        <property>
          <name>devcenter</name>
        </property>
      </activation>
      <properties>
        <devcenterAssetsDirectory>${project.basedir}/devcenter-app/assets</devcenterAssetsDirectory>
        <skipTests>true</skipTests>
        <maven.test.skip>true</maven.test.skip>
        <maven.test.failure.ignore>true</maven.test.failure.ignore>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.1.2</version>
            <executions>
              <execution>
                <id>copy-assets</id>
                <phase>install</phase>
                <goals>
                  <goal>copy</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>${project.groupId}</groupId>
                      <artifactId>${project.artifactId}</artifactId>
                      <version>${project.version}</version>
                      <type>${project.packaging}</type>
                      <overWrite>true</overWrite>
                    </artifactItem>
                  </artifactItems>
                  <outputDirectory>${devcenterAssetsDirectory}</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
